print("Welcome to the interactive Personal Data collector!")
name = input("Enter your Name = ")
age = int(input("Enter your Age = "))   
Current = int(input("Enter your Current year = "))   
Height = float(input("Enter your height = "))
Favourite = int(input("Enter your Favourite = "))
print("__________________________________________________________________")
print("Thank You! Here is your Information we collected!!")
print("__________________________________________________________________")

print(name,("type = ",type(name),"Memory address = ",id(name)))
print(age,("type = ",type(age),"Memory address = ",id(age)))
print(Height,("type = ",type(Height),"Memory address = ",id(Height)))
print(Favourite,("type = ",type(Favourite),"Memory address = ",id(Favourite)))
print("__________________________________________________________________")
birthyear = Current - age
print(f"Your birth year is approximately = {birthyear}")
print("__________________________________________________________________")
print("Thank you for using the personal data collector.Goodbye!!!")